/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triptec.gui;

/**
 *
 * @author sebas
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitle = new javax.swing.JLabel();
        jButtonManageTouristicSites = new javax.swing.JButton();
        jButtonCreateRoute = new javax.swing.JButton();
        jButtonSignIn = new javax.swing.JButton();
        jButtonCreateClientRoute = new javax.swing.JButton();
        jButtonShortestPath = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeltitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabeltitle.setText("TRIPTEC");

        jButtonManageTouristicSites.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonManageTouristicSites.setText("Tourist sites manager");
        jButtonManageTouristicSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageTouristicSitesActionPerformed(evt);
            }
        });

        jButtonCreateRoute.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCreateRoute.setText("Create route for the Official Tour ");

        jButtonSignIn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSignIn.setText("Sign in (Client)");

        jButtonCreateClientRoute.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCreateClientRoute.setText("Create Client's route");

        jButtonShortestPath.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonShortestPath.setText("Shortest Path recommendation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonManageTouristicSites)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCreateClientRoute)
                        .addGap(257, 257, 257))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonShortestPath)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(jButtonCreateRoute))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(304, 304, 304)
                            .addComponent(jLabeltitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(295, 295, 295)
                            .addComponent(jButtonSignIn))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltitle)
                .addGap(57, 57, 57)
                .addComponent(jButtonManageTouristicSites, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButtonCreateRoute)
                .addGap(65, 65, 65)
                .addComponent(jButtonSignIn)
                .addGap(62, 62, 62)
                .addComponent(jButtonCreateClientRoute)
                .addGap(53, 53, 53)
                .addComponent(jButtonShortestPath)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManageTouristicSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageTouristicSitesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManageTouristicSitesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateClientRoute;
    private javax.swing.JButton jButtonCreateRoute;
    private javax.swing.JButton jButtonManageTouristicSites;
    private javax.swing.JButton jButtonShortestPath;
    private javax.swing.JButton jButtonSignIn;
    private javax.swing.JLabel jLabeltitle;
    // End of variables declaration//GEN-END:variables
}
