/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triptec.gui;

import triptec.logic.TouristSiteManager;

/**
 *
 * @author sebas
 */
public class MainWindow extends javax.swing.JFrame {
     private TouristSiteManager touristsites;   

    public TouristSiteManager getTouristsites() {
        return touristsites;
    }

    public void setTouristsites(TouristSiteManager touristsites) {
        this.touristsites = touristsites;
    }
     
     
    
    
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitle = new javax.swing.JLabel();
        jButtonManageTouristicSites = new javax.swing.JButton();
        jButtonCreateRoute = new javax.swing.JButton();
        jButtonSignIn = new javax.swing.JButton();
        jButtonCreateClientRoute = new javax.swing.JButton();
        jButtonShortestPath = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeltitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabeltitle.setText("TRIPTEC");

        jButtonManageTouristicSites.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonManageTouristicSites.setText("Tourist sites manager");
        jButtonManageTouristicSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageTouristicSitesActionPerformed(evt);
            }
        });

        jButtonCreateRoute.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCreateRoute.setText("Create route for the Official Tour ");

        jButtonSignIn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSignIn.setText("Sign in (Client)");

        jButtonCreateClientRoute.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCreateClientRoute.setText("Create Client's route");

        jButtonShortestPath.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonShortestPath.setText("Shortest Path recommendation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabeltitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonManageTouristicSites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCreateRoute)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButtonSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCreateClientRoute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonShortestPath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltitle)
                .addGap(57, 57, 57)
                .addComponent(jButtonManageTouristicSites, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButtonCreateRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonCreateClientRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonShortestPath, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManageTouristicSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageTouristicSitesActionPerformed
        TouristSitesManagerWindow winTSM = new TouristSitesManagerWindow (this, rootPaneCheckingEnabled, this);
        winTSM.setVisible(true);
        winTSM.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_jButtonManageTouristicSitesActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateClientRoute;
    private javax.swing.JButton jButtonCreateRoute;
    private javax.swing.JButton jButtonManageTouristicSites;
    private javax.swing.JButton jButtonShortestPath;
    private javax.swing.JButton jButtonSignIn;
    private javax.swing.JLabel jLabeltitle;
    // End of variables declaration//GEN-END:variables
}
