/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triptec.gui;

/**
 *
 * @author sebas
 */
public class TouristSitesManagerWindow extends javax.swing.JDialog {
    MainWindow mainWindow;

    public MainWindow getMainWindow() {
        return mainWindow;
    }

    public void setMainWindow(MainWindow mainWindow) {
        this.mainWindow = mainWindow;
    }
    
    
  
    
    /**
     * Creates new form TouristSitesManWindow
     */
    public TouristSitesManagerWindow(java.awt.Frame parent, boolean modal, MainWindow mainWindow) {
        super(parent, modal);
        initComponents();
        this.mainWindow = mainWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAddwithAddress = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEditTouristSite = new javax.swing.JButton();
        jButtonDeleteTS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddLatLon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAddwithAddress.setText("Add location using the exact adress");
        jButtonAddwithAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddwithAddressActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonEditTouristSite.setText("Edit Tourist Site");

        jButtonDeleteTS.setText("Delete Tourist Site");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Create tour sites");

        jButtonAddLatLon.setText("Add location using latitude and longitude");
        jButtonAddLatLon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddLatLonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditTouristSite)
                            .addComponent(jButtonDeleteTS)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButtonAddLatLon)
                        .addGap(108, 108, 108)
                        .addComponent(jButtonAddwithAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddLatLon)
                            .addComponent(jButtonAddwithAddress))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jButtonEditTouristSite)
                        .addGap(54, 54, 54)
                        .addComponent(jButtonDeleteTS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddLatLonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddLatLonActionPerformed
        AddTSLatLonWindow addLATLON = new  AddTSLatLonWindow(this, rootPaneCheckingEnabled, this);
        addLATLON.setVisible(true);
        addLATLON.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

    }//GEN-LAST:event_jButtonAddLatLonActionPerformed

    private void jButtonAddwithAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddwithAddressActionPerformed
       AddTSAddressWindow addAddress = new  AddTSAddressWindow(this, rootPaneCheckingEnabled, this);
       addAddress.setVisible(true);
       addAddress.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_jButtonAddwithAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddLatLon;
    private javax.swing.JButton jButtonAddwithAddress;
    private javax.swing.JButton jButtonDeleteTS;
    private javax.swing.JButton jButtonEditTouristSite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
